//
// Created by 秦艽 on 2024/3/26.
//

#ifndef STUDENT_STATIC_VERIABLE_H
#define STUDENT_STATIC_VERIABLE_H

#define INCREMENT_ARRAY_SIZE_COEFFICIENT 5
#define DECREMENT_ARRAY_SIZE_COEFFICIENT 10
#define SCORE_MAIN_SUBJECT_MIN 0
#define SCORE_MAIN_SUBJECT_MAX 100
#define SPORT_SUBJECT_MIN 0
#define SPORT_SUBJECT_MAX 30
#define ONCE_SUBJECT_EXCELLENT 0.9
#define ONCE_SUBJECT_FINE 0.8
#define ONCE_SUBJECT_MIDDLE 0.7
#define ONCE_SUBJECT_PASS 0.6
#define ACTION_INCREMENT 'i'
#define ACTION_DECREMENT 'd'
#define FIND_ID 'I'
#define FIND_UID 'U'
#define FIND_EMAIL 'E'


#endif //STUDENT_STATIC_VERIABLE_H
